Vagrant.configure("2") do |config|
  # criar três VMs com um loop:
  (1..3).each do |i|
    # nomeando cada VM com a variável 'i':
    config.vm.define "swarm-#{i}" do |swarm|
      swarm.vm.box = "ubuntu/bionic64"
      swarm.vm.hostname = "node-#{i}"
      swarm.vm.network "private_network", ip: "192.168.56.1#{i}"

      # desativando a geração automática de uma nova chave SSH para cada máquina
      # criada pelo Vagrant:
      swarm.ssh.insert_key = false
      # definindo as chaves privadas que o Vagrant tentará usar ao conectar via
      # SSH dentro de cada VM:
      swarm.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
      # copiando chave pública (id_rsa.pub) para dentro de cada VM:
      swarm.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

      swarm.vm.provision "shell", inline: <<-SHELL
        # atualizando listas de repositórios:
        apt update

        # instalando dependências:
        apt install ca-certificates curl gnupg lsb-release -y

        # adicionando o repositório do Docker:
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # instalando o Docker:
        apt update
        apt install docker-ce docker-ce-cli containerd.io -y

        # iniciando e habilitando o serviço Docker:
        systemctl start docker
        systemctl enable docker

        # adicionando o usuário vagrant ao grupo docker:
        usermod -aG docker vagrant
      SHELL
    end
  end
end
